server.port=8080

spring.application.name=parksight-backend

python.api.url=https://parksight-ai-engine.onrender.com/predict_hotspots

logging.level.com.parksight=DEBUG
logging.level.org.springframework.web=INFO
